# RuboCop configuration file for actions

inherit_gem:
  rubocop-config-timedia:
    - config/base.yml
    - config/factory_bot.yml
    - config/rails.yml
    - config/rspec.yml

AllCops:
  TargetRubyVersion: 3.2

Gemspec/RequiredRubyVersion:
  Exclude:
    - rubocop/rubocop-config-timedia.gemspec
