# frozen_string_literal: true

source 'https://rubygems.org'

gemspec path: './rubocop'

# NOTE: 新しい Cop の定義を yaml に追加した際に CI が落ちた場合
#   * rubocop/rubocop-config-timedia.gemspec の runtime_dependency の最低バージョンを上げてください
#   * それに合わせて↓ のバージョンも上げてください
#
#   e.g. RuboCop 1.30.0 で追加された Cop のデフォルトを設定したい＆現在の RuboCop の最低バージョンが 1.27.0 である
#     * rubocop-config-timedia.gemspec
#       ```diff
#       - spec.add_runtime_dependency 'rubocop', '>= 1.27.0'
#       + spec.add_runtime_dependency 'rubocop', '>= 1.30.0'
#       ```
#     * Gemfile
#       ```diff
#       - gem 'rubocop', '~> 1.27.0'
#       + gem 'rubocop', '~> 1.30.0'
#       ```
#
gem 'rubocop', '~> 1.33.0'
gem 'rubocop-performance', '~> 1.13.0'
gem 'rubocop-rails', '~> 2.14.0'
gem 'rubocop-rspec', '~> 2.10.0'
